###Code in previous observations###
tv_steal_success_2017<-(16/18)
tv_steal_success_2018<-(13/17)


###Define successes###
TV_STEAL_SUCCESS<-c(TV_STEAL_SUCCESS_2017,TV_STEAL_SUCCESS_2018)

###Mean###
TV_STEAL_MEAN<-mean(TV_STEAL_SUCCESS)

###Standard Deviation###
TV_STEAL_STANDARD_DEVIATION<-sd(TV_STEAL_SUCCESS)


###Alpha and Beta Shape Parameters###

###Alpha###
TV_STEAL_ALPHA<-(((1-TV_STEAL_MEAN)/(TV_STEAL_STANDARD_DEVIATION^2))-(1/TV_STEAL_MEAN))*TV_STEAL_MEAN^2
TV_STEAL_ALPHA

###Beta###
TV_STEAL_BETA<-TV_STEAL_ALPHA*((1/TV_STEAL_MEAN)-1)
TV_STEAL_BETA
"CHECK"
TV_STEAL_ALPHA/(TV_STEAL_ALPHA+TV_STEAL_BETA)
(TV_STEAL_ALPHA*TV_STEAL_BETA)/((TV_STEAL_ALPHA+TV_STEAL_BETA)^2)*(TV_STEAL_ALPHA+TV_STEAL_BETA+1)

###Begin Distribution Calc###
TV_STEAL_PROB_DATA<-rbeta(10000, shape1=TV_STEAL_ALPHA, shape2=TV_STEAL_BETA)
TV_STEAL_MCE_SIMULATIONS<-rbinom(n=10000, size=20, prob=TV_STEAL_PROB_DATA)
hist(TV_STEAL_MCE_SIMULATIONS, main = "PRELIMENARY TYLER VILLAROMAN FUTURE STOLEN BASE RATE OUTLOOK", xlab="Simulated Successes out of 20 Attempts", ylab="Occurrences out of 10,000 simulations")
TV_STEAL_MCE_SIMULATIONS_MEAN<-(mean(TV_STEAL_SIMULATIONS))/20
TV_STEAL_MCE_SIMULATIONS_SD<-(sd(TV_STEAL_MCE_SIMULATIONS))/20
TV_STEAL_MCE_SIMULATIONS_SD

###Analyze Distribution####
TV_STEAL_PROB_DATA_VARIANCE<-var(TV_STEAL_PROB_DATA)
TV_STEAL_PROB_DATA_STANDARD_DEVIATION<-sqrt(TV_STEAL_PROB_DATA_VARIANCE)
TV_STEAL_PROB_DATA_STANDARD_DEVIATION
TV_2019_STEAL_RATE_BETTER_THAN_2018<-mean(TV_THETA<-((TV_STEAL_MCE_SIMULATIONS/20)>.76))


###Final###
TV_2019_STEAL_RATE_BETTER_THAN_2018